### ISSUE TITLE
Top Menu Bar Missing in Ubuntu

### ISSUE THREAD

**Issue by sejmodha** [rrwick/Bandage#1] opened 2015-03-27 17:48 UTC
Hi There,

I have installed Bandage in my Ubuntu machine and on my Mac. 
It works fine on the Mac but when I launch the executables in Ubuntu the top menu bar with File and View options is missing.
I didn't get any errors while building the tool and QT5 seems to be installed fine too.

Any help would be appreciated.
Sej

**Comment by rrwick** [comment] 2015-03-27 22:06
Sej,

In the version of Ubuntu I've tried (with the Unity desktop), the menu bar is at the very top of the screen, and it doesn't appear until you move the mouse to the region.  When the mouse is elsewhere, it will just say 'Bandage', but when the mouse is in the top bar, it changes to 'File', 'Tools', etc.  Is that not working for you?  If not, which version of Ubuntu are you using so I can try it myself?

You can also try downloading the statically-linked Linux version I put in the releases page.  That version (at least in my tests) puts the menu bar directly in the window, not at the top of the screen.

I hope that helps - let me know if you get it working!

Ryan

**Comment by sejmodha** [comment] 2015-03-30 10:54
Hi Ryan,
That works! Silly of me not to try that before posting the question here.

Thanks for your help.
Sej

**Comment by rrwick** [comment] 2015-03-30 13:17
Sej,

Not a problem.  I'll close this issue now, but feel free to ask about anything else!

Ryan

**Comment by sejmodha** [comment] 2015-03-30 13:51
Sorry about the confusion Ryan but I am unable to see the top menu bar on the Ubuntu 14.04 server.
![screenshot from 2015-03-30 14 51 26](https://cloud.githubusercontent.com/assets/6159960/6897536/4d068f6e-d6ec-11e4-82a3-9efc5c4135a7.png)

**Comment by rrwick** [comment] 2015-03-30 14:12
Sej,

Hmmm, I'll have to download Ubuntu 14.04 Server and try this myself.  I have successfully tested it on 14.04 Desktop, but perhaps there are some important differences.

In the mean time, there's a couple of things you could try.  Are you using the pre-built program that's linked to from the the Bandage page (also here: https://github.com/rrwick/Bandage/releases)?  If so, you could try the statically-linked version, named Bandage_Linux_static_v0.4.2.zip (only available here: https://github.com/rrwick/Bandage/releases).  In my tests, this puts the menu bar in the window itself.  It doesn't look consistent with the normal Unity look and feel, but might at least allow you to use the program.

Also, I'd be curious if you still have the same issue if you build Bandage from source, following the instructions here: https://github.com/rrwick/Bandage.

I'll let you know if I can replicate the issue on my install of 14.04 Server.

Ryan

**Comment by sejmodha** [comment] 2015-03-30 15:00
Hi Ryan,

I had build the tool from scratch and that version was missing the menu bar as well as the pre-built one.

Bandage_Linux_static_v0.4.2.zip seems to work, but it puts the menu bar in the window itself as you mentioned but at least it works!

Thanks for you help again.
Sej

**Comment by rrwick** [comment] 2015-03-31 03:22
Sej,

I haven't been able to reproduce the issue myself.  I did a clean install of 14.04 Server in a virtual machine, ran `sudo apt-get install ubuntu-desktop` to get the GUI, and then tried Bandage, which had a working menu bar.

However, a bit of Googling revealed that missing menu bars was a well-known problem for Qt applications, as seen [here](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619).  There are a few workarounds, each of which seems to put the menu bar into the window itself.

[This site](https://launchpad.net/appmenu-qt5) claims that the menu bar functionality requires Qt version >= 5.2.  My install of 14.04 has Qt 5.2.1, so perhaps that's why I'm not seeing the problem.  Can you check your version?  This works for me: `dpkg -s libqt5core5a`

If you are on an earlier version, then maybe a `sudo apt-get update` and `sudo apt-get upgrade` will fix the issue.  Even if you are on Qt 5.2+, you should probably try upgrading all your packages in case something else is the culprit.

Let me know how you go!

Ryan

**Comment by rrwick** [comment] 2015-05-08 07:25
Sej,

I haven't heard back from you, so I'm going to close this issue now.  If you're still experiencing the problem, even with a current version of Qt, let me know and I'll look into it more.

Ryan

**Closed by rrwick** 2015-05-08 07:25 UTC
